# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 15.0.0
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec gem install pry
      - run: bundle exec fastlane use_cert
      - run:
          name: Fastlane
          command: bundle exec fastlane build_release
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  # adhoc:
  #   macos:
  #     xcode: 14.2.0
  #   environment:
  #     FL_OUTPUT_DIR: output
  #     FASTLANE_LANE: adhoc
  #   steps:
  #     - checkout
  #     - run: bundle install
  #     - run:
  #         name: Fastlane
  #         command: bundle exec fastlane $FASTLANE_LANE
  #     - store_artifacts:
  #         path: output

workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
