# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 15.0.1
    steps:
      - checkout
      - run: xcodebuild archive -project "ios-dev-poc.xcodeproj" -scheme "ios-dev-poc" -destination generic/platform=iOS CODE_SIGN_IDENTITY=- AD_HOC_CODE_SIGNING_ALLOWED=YES COMPILER_INDEX_STORE_ENABLE=NO -allowProvisioningUpdates -archivePath ios-dev-poc.xcarchive

workflows:
  archive:
    jobs:
      - build-and-test
