# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 15.0.1
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec fastlane use_cert
      - run:
          name: Fastlane
          command: bundle exec fastlane upload_release
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
          requires:
            - build-and-test
