# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 15.0.0
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: Install Bundle
          command: bundle install     
      - run: 
          name: Setup iOS Certificate And Profile
          command: bundle exec fastlane use_cert
      - run:
          name: Fastlane
          command: bundle exec fastlane build_release
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
      - run: 
          name: Upload iOS App To App Store
          command: bundle exec fastlane upload_ipa_to_store

workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
