name: Mobile CICD

on:
  push:
    branches:
      - circle-ci-v3

jobs:
  submit_ios_app_to_app_store:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app

      - name: Install Bundle
        run: bundle install 

      - name: Setup iOS Certificate And Profile
        run: bundle exec fastlane use_cert

      - name: Build, Archive And Export App
        run: bundle exec fastlane build_release

      - name: list folder structure
        run: |
          brew install tree
          tree 


      - name: Upload iOS App To App Store
        run: bundle exec fastlane upload_ipa_to_store
